app.py
import jyserver.Flask as jsf
from flask import Flask, flash, render_template, request, Response, session
from werkzeug import secure_filename
from requests.auth import HTTPBasicAuth
import os
import sys
import pytesseract
import argparse
import cv2
import re
import time
import calendar
from PIL import Image, ImageTk
from camera import VideoCamera
from image import ImageProcess
import requests
import json
from api import api_blueprint
from routes import routes_blueprint
from mysql import Connection
from selenium import webdriver
from config import Config
from filehandling import HoldStatus
import threading
import face_recognition
import pickle
__author__ = 'Prabu <mprabu@gocontec.com>'
__source__ = ''
encodeListKnown = "global"
app = Flask(__name__)

app.register_blueprint(api_blueprint, url_prefix='/api')
app.register_blueprint(routes_blueprint, url_prefix='/')

# global camera
# camera = VideoCamera()
@jsf.use(app)
class App:
    def __init__(self):
        self.count = 5

    def increment(self):
        r = HoldStatus("").readFile("_scan")
        if r == "1":
            self.js.document.getElementById("on_status").style.display = "block"
            self.js.document.getElementById("on_status").style.color = "green"
            self.js.document.getElementById("on_status").innerHTML = "Valid"
        elif r =="2":
            self.js.document.getElementById("on_status").style.color = "green"
            self.js.document.getElementById("on_status").innerHTML = "Running"
        else:
            self.js.document.getElementById("on_status").style.display = "block"
            self.js.document.getElementById("on_status").style.color = "red"
            self.js.document.getElementById("on_status").innerHTML = "In-valid"

        r = HoldStatus("").readFile("_goodData")
        self.js.document.getElementById("dc_").innerHTML = r

        r = HoldStatus("").readFile("_processing")
        if r== "1":
            self.js.document.getElementById("on_bgp").innerHTML = "Processing"
        else:
            self.js.document.getElementById("on_bgp").innerHTML = "Waiting"

#background process happening without any refreshing
@app.route('/background_process_enable/<string:val>')
def background_process_enable(val):
    HoldStatus("0").writeFile(val,"_update")
    return ('{"nothing":1}')


@app.route('/video_feed/<string:user>')
def video_feed(user):
    return Response(gen( VideoCamera(), user),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


@app.route('/video_feed_cali/<string:user>')
def video_feed_cali(user):
    return Response(gen_cal( VideoCamera(), user),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


def gen(camera, user):
    while True:
        frame = camera.get_Singleframe(user)
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame[0] + b'\r\n\r\n')


def gen_cal(camera, user):
    while True:
        frame = camera.get_Caliberation(user)
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame[0] + b'\r\n\r\n')

@app.route('/getFileName')
def getFileName():
    return 'static/audio/UnitNotFound.mp3'

@app.route("/video", methods=['POST','GET'])
def ocr():
    if request.method == 'POST':
        HoldStatus("").writeFile("", "_serial")
        HoldStatus("").writeFile("", "_lastScan")
        HoldStatus("").writeFile("0", "_lastScanCount")
        HoldStatus("").writeFile("2", "_scan")
        HoldStatus("").writeFile("0", "_serialrowcount")
        HoldStatus("").writeFile("0", "_serialpostCount")
        HoldStatus("").writeFile("", "_goodData")
        HoldStatus("").writeFile("0", "_processing")
        dict = {}
        
        for value in Connection().getModels(request.form['customer'], request.form['model']):
           mdict1 = {value[1]:value[2]}
           dict.update(mdict1)
        HoldStatus("").writeFile(json.dumps(dict),"_validation")
        return App.render(render_template("ocr.html", user=111))

@app.route("/calibration", methods=['POST','GET'])
def calib():
    if request.method == 'GET':
        return App.render(render_template("calibration.html", user=1233))

@app.route("/logout", methods=['GET'])
def logout():
    session.clear()
    return App.render(render_template("index.html", error=""))

def maintenance():
    """ Background thread doing various maintenance tasks """
    readText = ImageProcess()
    while True:
        # do things...
        readText.readData()
        time.sleep(MAINTENANCE_INTERVAL)

def postingData():
    """ Background thread doing various maintenance tasks """
    readText = ImageProcess()
    while True:
        # do things...
        readText.postToDeepblu()
        time.sleep(MAINTENANCE_INTERVAL)

if __name__ == '__main__':
    app.secret_key = 'A0Zr98j/3yX R~XHHER!jmN]LWX/,?RT'
    # t1 = threading.Thread(target=onoff, name='t1')
    # t1.start()

    MAINTENANCE_INTERVAL = .1

    threading.Thread(target=maintenance, daemon=True).start()
    threading.Thread(target=postingData, daemon=True).start()
    app.run(host="0.0.0.0", port=5000, debug=True)

routes.py
from flask import Blueprint, render_template, request, Response, session, Flask, jsonify
from mysql import Connection
from filehandling import HoldStatus
from camera import VideoCamera
from requests.auth import HTTPBasicAuth
import requests
from config import Config
import json

routes_blueprint = Blueprint('routes', __name__,)


@routes_blueprint.route("")
def index():
  return render_template("index.html", error="")


@routes_blueprint.route("/receiving", methods=['GET', "POST"])
def receiving():
  if request.method == 'POST':
    response = requests.post(
      Config.API_USER_URL + 'users/login', data=json.dumps({"username": request.form['username'], "password": request.form['password'], "Site": "Matamoros"}),
      headers={'Content-Type': 'application/json'}
    )
    if response.status_code != 200:
      return render_template("index.html", error="Authentication Failed!")
    a = response.json()
    session['user'] = a['user']['userName']
    # session['user'] = 'a'
    response = requests.get(
        Config.API_URL + 'customers',
        headers={'Content-Type': 'application/json'}
    )
    a = response.json()
    HoldStatus("0").writeFile("0", "_update")
    HoldStatus("").writeFile("","_validation")
    return render_template("receiving.html", customers=a['results'], user=session['user'])
  if request.method == 'GET':
    response = requests.get(
        Config.API_URL + 'customers',
        headers={'Content-Type': 'application/json'}
    )
    a = response.json()
    HoldStatus("0").writeFile("0", "_update")
    HoldStatus("").writeFile("","_validation")
    return render_template("receiving.html",customers=a['results'], user=session['user'])


@routes_blueprint.route("/modeldsp", methods=['GET', "POST"])
def modeldsp():
  if request.method == 'POST':
    response = requests.post(
      Config.API_USER_URL + 'users/login', data=json.dumps({"username": request.form['username'], "password": request.form['password'], "Site": "Matamoros"}),
      headers={'Content-Type': 'application/json'}
    )
    if response.status_code != 200:
      return render_template("index.html", error="Authentication Failed!")
    a = response.json()
    session['user'] = a['user']['userName']
    # session['user'] = 'a'
    response = requests.get(
        Config.API_URL + 'customers',
        headers={'Content-Type': 'application/json'}
    )
    a = response.json()
    HoldStatus("0").writeFile("0", "_update")
    HoldStatus("").writeFile("","_validation")
    return render_template("modeldsp.html", customers=a['results'], user=session['user'])

  if request.method == 'GET':
    response = requests.get(
      Config.API_URL + 'customers',
      headers={'Content-Type': 'application/json'}
    )
    a = response.json()
    HoldStatus("0").writeFile("0", "_update")
    HoldStatus("").writeFile("", "_validation")
    return render_template("modeldsp.html", customers=a['results'], user=session['user'])


@routes_blueprint.route("/cusmodupd", methods=['GET', "POST"])
def selection():
  if request.method == 'GET':
    response = requests.get(
      Config.API_URL + 'customers',
      headers={'Content-Type': 'application/json'}
    )
    a = response.json()
    HoldStatus("0").writeFile("0", "_update")
    HoldStatus("").writeFile("", "_validation")
    return render_template("cusmodupd.html", customers=a['results'], user=session['user']) 

templates/Final Version/modeldsp.html
{% extends "layout.html" %} {% block content %}
<div class="content">
    <div class="row">
       <!-- <div class="col-md-4 col-sm-4 col-xs-12"></div>-->
        <div class="col-md-3 col-sm-4 col-xs-12" align="center">
            <span id="username" style="display: none">{{user}}</span>
            <!--- form starts here --->
            <form class="needs-validation" id="form1" method="POST" name="modeldsp">
                <div class="form-group inputEle">
                    <label for="model">Please select your model:</label>
                        <div>
                            <select id="model" name="model" class="form-control">
                            <option value="">SELECT</option>
                            </select>
                        </div>
                </div>
                <div class="inputEle">
                    <label class="form-label" for="nsets">No of Sets:</label>
                    <input type="number" class="form-control" id="nsets" placeholder="Enter No of Sets" required
                           min="0" max="6" autocomplete="off">
                </div>
                <textarea name="finaldata" id="finaldata" style="display: none;"></textarea>
            </form>
            <!--- form ends here --->
        </div>

            <!--- form starts here --->
        <div class="col-md-9 col-sm-4 col-xs-12" align="center">
            <form id="myform">
                <div class="recvsubmit" id="button">
                    <button class="btn btn-primary" type="submit">Save</button>
                </div>
                 <div id="cont"></div>  <!-- the container to add the TABLE -->
            </form>
            <!--- form ends here --->
        </div>

    </div>
</div>

<style type=""text/css">

.row { margin-top:50px;margin-bottom:50px;}
.inputEle {
	text-align: left !important;
	width:60%
}

.recvsubmit {
	float:left;
	margin-top:12%;
}

input {
text-align:left !important;
}
</style>

<script type="text/javascript">

$(document).ready(function(){
            $("#button").hide();

     $("#overlay").fadeIn();
     $.ajax({
        type: "GET",
        url: "api/modellist",
        data: {},
        contentType: "application/json",
        dataType: "json",
        success: function (response) {
          var m = {};
          $.each(response["results"], function (key, value) {
            $('#model').append($('<option></option>').val(value["2"]).html(value["2"]));
          });
          console.log(m);
          $("#overlay").fadeOut();
        },
      });

 });

 $(document).ready(function(){
    $("#nsets").change(function(){

        if(form1.model.value == "") {
            alert("Please Enter Model!");
            return false;
        }

        // ------   Remove table "modTable" ------
        if (document.getElementById("modTable")) {
            var empTab1 = document.getElementById('modTable');
            empTab1.remove();
            }

        var rowcount = document.getElementById("nsets").value;
        if (rowcount <=0) {
            $("#button").hide();
        } else {
            $("#button").show();
        }

        if (rowcount >=1) {
            $("#button").show();
            var arrHead = new Array();	// array for header.
            arrHead = ['Label Name', 'Minimum Size', 'Maximum Size', 'ReqularExp', 'Pallet Count'];

         // ------   Create table "modTable" ------
                var modTable = document.createElement('table');
            modTable.setAttribute('id', 'modTable'); // table id.
            modTable.setAttribute('class', 'table');
            modTable.setAttribute("style","border:3px;");

                var tr = modTable.insertRow(-1);
                    for (var h = 0; h < arrHead.length; h++) {
                        var th = document.createElement('th'); // create table headers
                        th.innerHTML = arrHead[h];
                        tr.appendChild(th);
                    }
                var div = document.getElementById('cont');
                div.appendChild(modTable);  // add the TABLE to the container.

            var empTab = document.getElementById('modTable');

            for (var d = 1; d <= rowcount; d++) {

                tr = empTab.insertRow(d);
                var rowid = 'row' + d;             // Setting Row ID
                tr.setAttribute('id', rowid);

                    for (var c = 0; c < arrHead.length; c++) {
                        var td = document.createElement('td'); // table definition.
                        td = tr.insertCell(c);

                            if (c == 3) {      // the first column.
                            // add a button in every new row in the first column.
                            var SELECT = document.createElement('SELECT');

                                var colid1 = 'col' + d;
                                SELECT.setAttribute('class','form-control');
                                SELECT.setAttribute('required', 'true');
                                SELECT.setAttribute('id', colid1);
                                SELECT.setAttribute('size','1');
                                SELECT.setAttribute('type', 'text');

                            var OPT1 = document.createElement('OPTION');
                                OPT1.value = "";
                                OPT1.text = "Select";
                                SELECT.add(OPT1);
                            var OPT2 = document.createElement('OPTION');
                                OPT2.value = OPT2.text = "^[0-9A-Z]+$";
                                SELECT.add(OPT2);
                            var OPT3 = document.createElement('OPTION');
                                OPT3.value = OPT3.text = "^S[A-Z]+$";
                                SELECT.add(OPT3);
                            var OPT4 = document.createElement('OPTION');
                                OPT4.value = OPT4.text = "^0H[0-9A-Z]+$";
                                SELECT.add(OPT4);
                            var OPT5 = document.createElement('OPTION');
                                OPT5.value = OPT5.text = "^[0-9-0-9]+$";
                                SELECT.add(OPT5);

                            td.appendChild(SELECT);

                            } else {

                                // 2nd, 3rd and 4th column, will have textbox.
                                var ele = document.createElement('input');
                                ele.setAttribute('type', 'text');
                                if (c == 0) {
                                    ele.setAttribute('type', 'text');
                                }
                                if (c == 1 || c == 2 || c == 4) {
                                    ele.setAttribute('type', 'number');
                                }
                                var colid = 'col' + d;             // Setting Column ID
                                ele.setAttribute('id', colid);
                                ele.setAttribute('required', 'true');
                                ele.setAttribute('autocomplete', 'off');
                                ele.setAttribute('class','form-control');
                                ele.setAttribute('min','1');

                                td.appendChild(ele);
                            }

                    }

            }
        }

    });
 });
</script>

<script type="text/javascript">
button.addEventListener('click', function() {
    document.getElementById("button").disabled = true;
    alert('world');
});
</script>

<script type="text/javascript">
    var form = document.getElementById("myform")
    form.addEventListener('submit',function(event){
        event.preventDefault()

        document.getElementById("button").disabled = true;

        slash = '\\';
        char1 = '": "{';
        char2 = '"model';
        char3 = '": ';
        char4 = '"dcCount';
        char5 = '": ';
        char6 = '"data';
        quote = '"';
        qutsem = '":';


        var model1 = document.getElementById("model").value;
        var num1 = document.getElementById("nsets").value;
        var tab1 = document.getElementById("modTable")

        res1 =  quote + model1 +
                char1 + slash + char2 + slash + char3 + slash + quote + model1 + slash + quote + ',' + slash + char4
                + slash + char5 + num1 + ',' + slash + char6 + slash + qutsem ;

        qutat = '"';
        semi = ':'
        opnpra = '{';
        clspra = '}';
        comma = ',';
        opbx = '[';
        clbx = ']';
        space = ' ';

        var data = "";   // Initialising variable "data"

            for (var rlen = 1; rlen <= num1; rlen++) {

                for (var clen = 0; clen < 5; clen++) {
                    var element = tab1.rows.item(rlen).cells[clen];

                    if (element.childNodes[0].getAttribute('type') == 'text') {
                        if (clen == 0){
                            var name1 = element.childNodes[0].value;
                        }
                    }
                    if (element.childNodes[0].getAttribute('type') == 'text') {
                        if (clen == 3){
                            var colnum = "col1" + clen
                            var reqexp1 =  element.childNodes[0].value;
                        }
                    }
                    if (element.childNodes[0].getAttribute('type') == 'number') {
                        if (clen == 1){
                            var minsize1 = element.childNodes[0].value;
                        }
                        if (clen == 2){
                            var maxsize1 = element.childNodes[0].value;
                        }
                        if (clen == 4){
                            var pallet1 = element.childNodes[0].value;
                        }

                    }

                    var sort1 = rlen - 1;
                }

                if (rlen == 1) {

                    data1 = opbx + opnpra
                            + slash + qutat + "label" + slash + qutat + semi+ space + slash + qutat + name1
                                    + slash + qutat + comma
                            + slash + qutat + "min" + slash + qutat + semi+ space + minsize1 + comma
                            + slash + qutat + "max" + slash + qutat + semi+ space + maxsize1 + comma
                            + space + slash + qutat + "regularExp" + slash + qutat + semi+ space + slash
                                    + qutat + reqexp1 + slash + qutat + comma
                            + space + slash + qutat + "sort" + slash + qutat + semi+ space + slash
                                    + qutat + sort1 + slash + qutat + comma
                            + space + slash + qutat + "palletcount" + slash + qutat + semi+ space + slash + qutat
                                    + pallet1 + slash + qutat + space + clspra;
                var data2 =  data1;
                }
                if (rlen > 1) {

                   data1 = comma + opnpra + space
                            + slash + qutat + "label" + slash + qutat + semi+ space + slash + qutat + name1 + slash
                                    + qutat + comma + space
                            + slash + qutat + "min" + slash + qutat + semi+ space + minsize1 + comma
                            + slash + qutat + "max" + slash + qutat + semi+ space + maxsize1 + comma
                            + space + slash + qutat + "regularExp" + slash + qutat + semi+ space + slash + qutat
                                    + reqexp1 + slash + qutat + comma
                            + space + slash + qutat + "sort" + slash + qutat + semi+ space + slash + qutat
                                    + sort1 + slash + qutat + clspra;
                   data2 =  data2 + data1;
                }

                data1 = "";   // // Initialising variable "data1"

            }

        result = res1 + data2 + clbx + clspra + qutat;

        result1 = data2 + clbx + clspra + qutat;

        document.getElementById("finaldata").value = result;

        var mydata = document.getElementById("finaldata").value;

        var result2 = {
           m_name: model1,
           m_data: mydata
        };

        $.ajax({
            type: "POST",
            url: "api/insertmodeldata",
            data: JSON.stringify(result2),
            contentType: "application/json",
            dataType: "json",
            success: function (response) {
                swal({
                    title: "Successfully Saved!",
                    text: response.scriptstatus,
                    icon: "success",
                    button: "Ok",
                    type: "success"
                    }).then(function() {
                    // Redirect the user
                    window.location.reload();
                    console.log('Successfully Saved');
                    });
            },
        });

    });
</script>

{% endblock %}

templates/cusmodupd.html
{% extends "layout.html" %} {% block content %}
<div id="centerDiv">
  <div class="upload-form">
    <span id="username" style="display: none">{{user}}</span>
    <form method="POST" name="cusmodupd" id="cusmodupd">
      <div class="form-group">
        <label for="customer">Customer</label>
        <div>
          <select id="customer" name="customer" class="form-control">
            <option value="">SELECT</option>
           </select>
        </div>
      </div>
      <div class="form-group">
        <label for="model">Model</label>
        <div>
          <select id="model" name="model" class="form-control">
            <option value="">SELECT</option>
          </select>
        </div>
        </div>
      <div class="form-group">
        <div id="button">
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
      </div>
      
    </form>
  </div>
</div>

<script type="text/javascript">

  $(document).ready(function(){

                 // Clearing old contents before add new options
            $('#customer').find('option').remove();
            var x = document.getElementById("customer");
                // Default value
            var option = document.createElement("option");
            option.text = "SELECT";
            option.value = "";
            x.add(option);
            $("#overlay").fadeIn();

            $.ajax({
              type: "GET",
              url: "api/customers",
              data: {},
              contentType: "application/json",
              dataType: "json",
              success: function (response) {
                var m = {};
                $.each(response["results"], function (key, value) {
                  $('#customer').append($('<option></option>').val(value["1"]).html(value["2"]));
                });
                console.log(m);
                $("#overlay").fadeOut();
                },
            });

                  // Clearing old contents before add new options
            $('#model').find('option').remove();
            var y = document.getElementById("model");
            var option = document.createElement("option");
            option.text = "SELECT";
            option.value = "";
            y.add(option);

            $("#overlay").fadeIn();
            $.ajax({
              type: "GET",
              url: "api/modellist",
              data: {},
              contentType: "application/json",
              dataType: "json",
              success: function (response) {
                var m = {};
                $.each(response["results"], function (key, value) {
                  $('#model').append($('<option></option>').val(value["1"]).html(value["2"]));
                });
                console.log(m);
                $("#overlay").fadeOut();
                },
            });
});

</script>

<script type="text/javascript">
              // Customer's ID value
    $("#customer").change(function(){
    m_cust1 = $(this).find(":selected").attr("value");
    });
              // Model's ID value
    $("#model").change(function(){
     m_model1 = $(this).find(":selected").attr("value");
    });
</script>

<script type="text/javascript">
    var form = document.getElementById("cusmodupd")

    form.addEventListener('submit',function(event){
        event.preventDefault()

        var result2 = {
           m_cust2: m_cust1,
           m_model2: m_model1
        };

        $.ajax({
            type: "POST",
            url: "api/insertcustmodel",
            data: JSON.stringify(result2),
            contentType: "application/json",
            dataType: "json",
            success: function (response) {
                swal({
                    title: "Successfully Saved!",
                    text: response.scriptstatus,
                    icon: "success",
                    button: "Ok",
                    type: "success"
                    }).then(function() {
                    // Redirect the user
                    window.location.reload();
                    console.log('Successfully Saved');
                    });
            },
        });

    })
</script>

{% endblock %}

templates/index.html
{% extends "layout.html" %} {% block content %} {% if error %}
<div class="alert alert-danger alert-dismissible ">{{error}}</div>
{% endif %}
<div id="centerDiv">
  <div class="container upload-form login">
    <div class="form-container off-canvas">
      <div class="login-screen">
        <div class="app-title">
          <h1>Login</h1>
        </div>
        <form role="form" class="form-signin" action="/receiving" method="POST">
          <div class="form-group">
            <input placeholder="Username" type="text" class="form-control" name="username" id="username"
              aria-required="true" aria-invalid="true" required />
          </div>

          <div class="form-group">
            <input placeholder="Password" type="password" class="form-control" name="password" id="password"
              aria-required="true" aria-invalid="true" required />
          </div>

          <button class="btn btn-lg btn-primary btn-block" type="submit">
            Sign in
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.alert').delay(3000).fadeOut();
  var $loginForm = $(".form-signin"),
    $login_text_fields = $loginForm.find("input[type='text']");

  $(".login-logo,.form-container").removeClass("off-canvas");

  function _form_success_aria(label) {
    var target = label.parent().find("input");
    target.attr("aria-invalid", "false");
  }

  function _form_error_aria(validator) {
    console.log(validator.target.elements[0]);
  }
</script>
{% endblock %}

templates/ocr.html
{% extends "layout.html" %} {% block content %}
<div id="centerDivVideo">
<p id="count" style="display: none">0</p>
<button id="checkStatus" onclick="server.increment()" style="display: none">
  0
</button>
<div id="user" style="display: none">{{user}}</div>
<div class="ocr_head">
  <h2>OCR Receiving</h2>
</div>
<div class="ocr_head_button">
  <a href="{{ url_for('routes.receiving')}}" class="btn btn-primary" >Next Batch</a>
  {{value}}
</div>
<div class="ocr_content">
  <div class="ocr_body">
    <img
      class="ocr_bg"
      class="center"
      src="{{ url_for('video_feed', user=user) }}"
    />
    <div style="clear: both;"></div>
  <div class="ocr_value">
    <ul>
      <li>
        <b>Background:</b>
        <span id="bgp_"><span id="on_bgp"></span></span></li>
      <li>
        <b>Label Found:</b>
        <span id="label_">
          <span id="on_status"></span>
          <span id="off_status"></span>
        </span>
      </li>
      <li><b>Dc Status</b> <span id="dc_"></span></li>
    </ul>
    <audio id="mySong" src=""></audio>
  </div>

</div>
<script type="text/javascript">
  $(document).ready(function () {
    setInterval(function () {
      if ($("#user").html() != "") {
        $("#checkStatus").click();
      }


    }, 3000);

    $("#element").click(function(){
      var xhr = new XMLHttpRequest();
      xhr.open('GET', '/getFileName', true);
      xhr.send();

      xhr.onreadystatechange = function() {
        if (this.readyState == 4) {
        var filePath = this.responseText;
        var audio = document.getElementById('mySong');
        audio.src = filePath;
        audio.load();
          audio.oncanplaythrough = function() {
            this.play();
          }
        }
      }
    });
  });
</script>
<script>
  
  
  </script>
  </div>
  </div>
{% endblock %}

templates/test1.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<div class="row" style="z-index:0;">
  <div class="col-md-12">
    <table id="detailTable" class="table table-bordered table-sm">
      <thead class="thead-light" style="text-align:center">
        <tr>
          <th style="width:130px;">Date</th>
          <th style="width:300px;">Particulars</th>
          <th style="width:10px;">C.B.F</th>
          <th style="width:180px;">Dr. Amount</th>
          <th style="width:180px;">Cr. Amount</th>
          <th style="width:200px;">Balance</th>
          <th style="width:10px;">Opt</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td> <input type='text' value='11-12-2018' /> </td>
          <td> <input type='text' value='Cash' /> </td>
          <td> <input type='text' value='' /> </td>
          <td> <input type='text' value='20000' /> </td>
          <td> <input type='text' value='15000' /> </td>
          <td> <input type='text' value='-5000' /> </td>
          <td> <input type='button' value='Delete' /> </td>
      </tbody>
    </table>
  </div>
  <button type="button" class='btn btn-success'>Show</button>
</div>
  </div>
  <button onclick="myFunction()">Try it</button>
    <p id="demo"></p>
</div>
<script type="text/javascript">
function myFunction() {
  document.getElementById("demo").innerHTML = "Hello World!";
}
</script>

templates/test11.html
<html>
<head>
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $( document ).ready(function() {
            $("#providersFormElementsTable").html("<tr><td>Nickname</td><td><input type='text' id='nickname' name='nickname'></td></tr><tr><td>CA Number</td><td><input type='text' id='account' name='account'></td></tr>");
        });
    </script>
</head>

<body>
    <table border="0" cellpadding="0" width="100%" id='providersFormElementsTable'> </table>
</body></html>

templates/test15.html
<script>
var maxID = 0;
function getTemplateRow() {
var x = document.getElementById("templateRow").cloneNode(true);
x.id = "";
x.style.display = "";
x.innerHTML = x.innerHTML.replace(/{id}/, ++maxID);
return x;
}
function addRow() {
var t = document.getElementById("theTable");
var rows = t.getElementsByTagName("tr");
var r = rows[rows.length - 1];
r.parentNode.insertBefore(getTemplateRow(), r);

}
</script>


<table id="theTable">
<tr>
<td>id</td>
<td>name</td>
</tr>
<tr id="templateRow" style="display:none">
<td>{id}</td>
<td><input /></td>
</tr>
</table>


<button onclick="addRow();">Go</button>